spring.application.name=hospitalManagement

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/HMS
spring.datasource.username=postgres
spring.datasource.password=vamsi2001

server.servlet.context-path=/api/v1
#security
spring.security.user.name=test
spring.security.user.password=test
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql